### ISSUE TITLE
[Feature Request]: Add button dropdown (similar to the one in bootstrap)

### ISSUE THREAD

**Issue by toliv3** [scania-digital-design-system/tegel#120]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/sdds-website/issues) reported
- [X] I have read the contribution [guidelines](https://github.com/mmexvr/sdds/blob/master/CONTRIBUTING.md)
- [X] I have checked the lastest version if the feature exist there

### Type of feature request

Functionality

### What is your feature request?

As we have a limited ammount of types of buttons, when we have components that work as a dashboard and allow the user to take many actions, with just primary/secondary/ghost options, the experience is very poor.

### Background

The need for organizing similar actions into groups and simplify the user interface.

[AB#2320](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2320)

**Comment by mJarsater** [comment]
This feature request is noted and added to our backlog, will need both design investigation and development work.
