### ISSUE TITLE
[Feature Request]: Label-positon for the datetime 

### ISSUE THREAD

**Issue by UmarAli6** [scania-digital-design-system/tegel#151]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/tegel/issues) reported
- [X] I have checked the latest version if the feature exist there

### Type of feature request

Functionality

### What is your feature request?

I would like the Datetime component to have a labelPosition propetry so you can position the label as how you want it. There exists a label but it seems to be positioned outside.

### Background

We are replacing Angular Material components with the Tegel ones and the angular material datetime has a labelPosition property.

### Goals and objectives

labelPosition as exists in eg textfield or dropdown

### Timeline

Before week 27

### Contact information

umar.ali@scania.com

**Comment by mJarsater** [comment]
Hi @UmarAli6,

thanks for your request. Unfortunately this is not something we can implement at the moment. This goes against the design of our date picker and would require a full redesign of the component. 

If this is functionality you need today I would recommend you stay with the one from Angular Material, or other third party library.
