### ISSUE TITLE
[Bug report]: sdds-textfield read only icon and icon slot conflict

### ISSUE THREAD

**Issue by toliv3** [scania-digital-design-system/tegel#23]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/sdds-website/issues) reported.
- [X] I have read the contribution [guidelines](https://github.com/mmexvr/sdds/blob/master/CONTRIBUTING.md).
- [X] I have checked the lastest version if the bug exist there. See all avaliable packages at [npmJS.com](https://www.npmjs.com/search?q=%40scania)
- [X] I have made sure that the issue comes from SDDS packages by removing SDDS from my project as a test.
- [X] I have followed the installation guide.

### Package

@scania/components

### Package versions

@latest

### Browser

Chrome

### Framework

Angular

### Reproduction steps

Add an sdds-textfield with an icon in the sdds-suffix slot.
Set this textfield to read only state.
See as both icons overlap.

![image](https://user-images.githubusercontent.com/111114201/233348101-1c5d7fb0-0cd4-4c55-a770-fc7999b4f077.png)

My suggestion would be adding a prop to disable the read only icon if needed.

### Code example

<div>....

### Screenshots

Add/Copy screenshot here

### Expected behaviour

Icons shouldn't overlap.

### Console errors

Add warning/error message

**Comment by mJarsater** [comment]
Hi! Just a quick update on this issue. We have taken a look at it in the team and the next step is for design to determine how we want to handle these kind of issues.

**Comment by mJarsater** [comment]
This bug report is noted and added to our backlog, will need both design investigation and development work.
