### ISSUE TITLE
[Feature Request]: Utility class for outline options

### ISSUE THREAD

**Issue by mmexvr** [scania-digital-design-system/tegel#24]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/sdds-website/issues) reported
- [X] I have read the contribution [guidelines](https://github.com/mmexvr/sdds/blob/master/CONTRIBUTING.md)
- [X] I have checked the lastest version if the feature exist there

### Type of feature request

Functionality

### What is your feature request?

One utility class that would be really nice to add is `outline: none !important;` (maybe more outline options) 

### Background

Instead of adding outline: none on a 

```button { outline: none !improtant }```

### Idea

sdds-outline-rm {
outline: none;
}

Should be easy to add in the utility classes  https://tegel.scania.com/development/utility-classes

### Goals and objectives

Easy way for maintaining a outline option in CSS

**Comment by mJarsater** [comment]
@mmexvr We'd love to hear more about why you would need this feature. Is this purely a stylistic choice or is the outline causing issues for you in any other way?

**Comment by mJarsater** [comment]
> Like the other utility classes that you guys provide, it would be nice to have some options on outline. I felt it would be nice since we use some of the utility classes already it would make sense to have one for outline also, maybe not just ":none", but other options also.
> 
> https://tegel.scania.com/development/utility-classes
> 
> I have create my own solution for this, but I think this would be good also to maybe come from tegel? Not a big problem if this is not something that shouldn't come for tegel. Then you can close this

Alrightero! Thanks for the input. We'll discuss it within the team and then we'll see how we move on from there. Closing this issue for now.
