### ISSUE TITLE
[Bug report]: sddsTextArea scrolling z-index conflict with label when label-position = inside

### ISSUE THREAD

**Issue by toliv3** [scania-digital-design-system/tegel#25]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/sdds-website/issues) reported.
- [X] I have read the contribution [guidelines](https://github.com/mmexvr/sdds/blob/master/CONTRIBUTING.md).
- [X] I have checked the lastest version if the bug exist there. See all avaliable packages at [npmJS.com](https://www.npmjs.com/search?q=%40scania)
- [X] I have made sure that the issue comes from SDDS packages by removing SDDS from my project as a test.
- [X] I have followed the installation guide.

### Package

@scania/components

### Package versions

@scania/components@4.10.7

### Browser

Chrome

### Framework

Angular

### Version

Angular 15

### Reproduction steps

1. Add a sdds_textarea
2. Set label inside property
3. Type enough text so there is a vertical scroll bar. (both normal & read-only mode)

### Code example

<div>....

### Screenshots

![image](https://user-images.githubusercontent.com/111114201/226905056-90ec06be-e808-466d-ae63-493f424c36ee.png)
![image](https://user-images.githubusercontent.com/111114201/226905276-299a660c-23a1-43b0-8799-36ad749b4ddc.png)

### Expected behaviour

The text should not conflict with the label inside z-index

### Console errors

Add warning/error message

### Contact information

thiago.oliveira@scania.com

**Comment by alexandereneroth** [comment]
We have put this in our internal backlog and our designers will review it.
Closing this, thanks for the feedback!

**Comment by mJarsater** [comment]
This bug report is noted and added to our backlog, will need both design investigation and development work.
