### ISSUE TITLE
[Feature Request]: Progress bar

### ISSUE THREAD

**Issue by GJagad** [scania-digital-design-system/tegel#26]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/sdds-website/issues) reported
- [X] I have read the contribution [guidelines](https://github.com/mmexvr/sdds/blob/master/CONTRIBUTING.md)
- [X] I have checked the lastest version if the feature exist there

### Type of feature request

Design

### What is your feature request?

A standard progress bar that can be used to indicate to the users as they work on step-by-step task based on the instruction received from a system function. Good to have percentage as an option.

### Background

We have a picking solution for line feeding where user needs to pick articles based on the instructions from the application. Would be good to have a progress indicator to encourage and have the user informed of the overall progress.

### Resources

https://carbondesignsystem.com/components/progress-bar/usage/

### Contact information

ganesh.babu.jagadeesan@scania.com

**Comment by alexandereneroth** [comment]
We have put this in our internal backlog and our designers will review it.

Closing this for now.
Thanks for the suggestion!

**Comment by mJarsater** [comment]
This feature request is noted and added to our backlog, will need both design investigation and development work.
