### ISSUE TITLE
Issue with Cell Single in Figma

### ISSUE THREAD

**Issue by joakimolin** [scania-digital-design-system/tegel#342]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/sdds-website/issues) reported
- [X] I have read the contribution [guidelines](https://github.com/mmexvr/sdds/blob/master/CONTRIBUTING.md)
- [X] I have checked the lastest version if the feature exist there

### Type of feature request

Design

### What is your feature request?

There is an issue with the Cell Single component in Figma, when you select Size as "Compact" and Col divider as "Left & right". The right "Divider Vertical" doesn't change it's position when changing the cell width. 

### Background

To make it work I have to detach the component and make the changes myself. Then I lose the ability to easily change the state of the component.

### Idea

For "Divider Vertical" (the one in the right side of the cell) the following needs to be done:
- Set Constraints to "Right" for "Divider Vertical".
- Change the order of the two Divider Verticals in the Layers panel.

### Contact information

joakim.olin@scania.com

**Comment by mJarsater** [comment]
This bug report is noted and added to our backlog, will need both design investigation and development work.
