### ISSUE TITLE
[Feature Request]: Remove Dotenv from the dependencies

### ISSUE THREAD

**Issue by gokberknur** [scania-digital-design-system/tegel#407]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/tegel/issues) reported
- [X] I have checked the latest version if the feature exist there

### Type of feature request

Functionality

### What is your feature request?

Hi guys, not a big issue but  I saw you updated the node version. 

with the node 20 you no longer need dotenv as dependencies. 

### Background

you can read a bit more here: https://dev.to/cjreads665/nodejs-2060-say-goodbye-to-dotenv-2ijl

### Idea

make dependency array as clean as possible :)

**Comment by mJarsater** [comment]
Lovely!
