### ISSUE TITLE
[Bug report]: Cannot read properties of null (reading 'getBoundingClientRect') - tds-slider

### ISSUE THREAD

**Issue by gokberknur** [scania-digital-design-system/tegel#410]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/tegel/issues) reported.
- [X] I have checked the latest version if the bug exist there. See all available packages at [npmJS.com](https://www.npmjs.com/package/@scania/tegel)
- [X] I have followed the installation guide.

### Package versions

@scania/tegel@1.1.0

### Browser

Chrome

### Framework

Angular

### Version

Angular 16

### Reproduction steps

1. Add tds-slider on your page
2. visit page where is your slider component (no error here logged)
3. then visit another page 
4. come back to page where is your tds-slider( now you will see error)
...

<img width="956" alt="Screenshot 2023-11-06 at 17 08 31" src="https://github.com/scania-digital-design-system/tegel/assets/5589187/eafde96c-48a0-4983-8b4d-381506d83df3">

### Code example

`  <tds-slider
                min="0"
                max="500"
                step="1"
                value="50"
                ticks="4"
                show-tick-numbers
                snap
                label="Range"
                tooltip
                ngDefaultControl
                #rangeSlider
                [(ngModel)]="radius"
                controls
                thumb-size="sm"
              ></tds-slider>`

### Screenshots

Add/Copy screenshot here
<img width="956" alt="Screenshot 2023-11-06 at 17 08 31" src="https://github.com/scania-digital-design-system/tegel/assets/5589187/7ae5b491-a8a6-406a-b2ea-e856bc10ecab">

### Expected behaviour

Component "tds-slider" should not log any errors.

### Console errors

cpoi.component.html:72 TypeError: Cannot read properties of null (reading 'getBoundingClientRect')

**Comment by alfredskeden** [comment]
Hello @gokberknur 
I've tried to reproduce this error but without success.

Can you please checkout my code here https://github.com/alfredskeden/tegel-tds-slider-test/tree/main

And please update that code there to make it break by opening a PR in there? Or am I missing something in your produce steps to get this error? Would help a alot. thanks
best regards

**Comment by theJohnnyMe** [comment]
I am closing it as the fix is released and did help.
