### ISSUE TITLE
[Bug report]: Enabling the compactDesign prop on tds-table overrides the padding from the disablePadding prop on the tds-body-cell.

### ISSUE THREAD

**Issue by adarean5** [scania-digital-design-system/tegel#469]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/tegel/issues) reported.
- [X] I have checked the latest version if the bug exist there. See all available packages at [npmJS.com](https://www.npmjs.com/package/@scania/tegel)
- [X] I have followed the installation guide.

### Package versions

@scania/tegel: 1.3.3

### Browser

Chrome

### Framework

Angular

### Version

Angular 16

### Reproduction steps

1. Create a tegel table containing tds-body-cell elements.
2. Set the `compactDesign` prop on the `tds-table` component to `true`.
3. Set the `disablePadding` prop on the `tds-body-cell` to `true`.

Result: The padding is still applied to the cell.

### Code example

```html
<tds-table [compactDesign]="true">
    <tds-table-header>
        <tds-header-cell
            cellKey="description"
            cellValue="Description"
        ></tds-header-cell>
    </tds-table-header>
    <tds-table-body>
        <tds-table-body-row>
            <tds-body-cell
                cellKey="description"
                cellValue="Description"
                [disablePadding]="true"
            ></tds-body-cell>
        </tds-table-body-row>
    </tds-table-body>
</tds-table>
```

### Screenshots

In the dev console, it can be observed that the compact styling overrides the no-padding styling.
![MicrosoftTeams-image](https://github.com/scania-digital-design-system/tegel/assets/15961301/fad5a43b-8b35-4359-a734-9d20e3581e95)

### Expected behaviour

After applying the `disablePadding` prop to the cell I would expect the cell not to have padding.

### Console errors

None

### Contact information

jernej.strazisar@scania.com

**Comment by nathalielindqvist** [comment]
Hi @adarean5! Thank you for reporting this, a fix for the issue has now been merged and will be available in the next release! :)

**Comment by adarean5** [comment]
Awesome, thank you!
