### ISSUE TITLE
[Bug report]: Disabled dropdown (filter) can still be opened

### ISSUE THREAD

**Issue by mJarsater** [scania-digital-design-system/tegel#486]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/tegel/issues) reported.
- [X] I have checked the latest version if the bug exist there. See all available packages at [npmJS.com](https://www.npmjs.com/package/@scania/tegel)
- [X] I have followed the installation guide.

### Package versions

@scania/tegel@1.4.0

### Browser

Chrome

### Framework

Plain HTML

### Reproduction steps

1. Go to storybook
2. Go to Dropdown
3. Set it to `filter` using the controls
4. Disable it using the controls
5. Click the arrow icon
6. The dropdown still opens.

### Code example

-

### Screenshots

https://github.com/scania-digital-design-system/tegel/assets/62651103/fbc0f31f-06a6-48f0-8d70-14cf3f9c870b

### Expected behaviour

The dropdown should never open when it is disabled, no matter the variant/type.

### Console errors

-

**Comment by timrombergjakobsson** [comment]
Hey @mJarsater! Tried to recreate this one both locally and https://tds-storybook.tegel.scania.com/?path=/docs/components-dropdown--default, but could not? Emelie failed to recreate it also.

**Comment by mJarsater** [comment]
Sorry, missed to highlight that this is for the `filter` version: 
https://tds-storybook.tegel.scania.com/?path=/story/components-dropdown--default&args=filter:true;disabled:true&globals=backgrounds.value:!hex(F9FAFB)

https://github.com/scania-digital-design-system/tegel/assets/62651103/8bfd75a1-5892-40a2-b67a-51c633178152

**Comment by timrombergjakobsson** [comment]
> @timrombergjakobsson
> 
> Sorry, missed to highlight that this is for the `filter` version: https://tds-storybook.tegel.scania.com/?path=/story/components-dropdown--default&args=filter:true;disabled:true&globals=backgrounds.value:!hex(F9FAFB)
> 
>  Screen.Recording.2024-01-18.at.12.33.02.mov

Ah ok! Nice find man!
