### ISSUE TITLE
[Bug report]: Missing controls

### ISSUE THREAD

**Issue by cfarvidson** [scania-digital-design-system/tegel#491]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/tegel/issues) reported.
- [X] I have checked the latest version if the bug exist there. See all available packages at [npmJS.com](https://www.npmjs.com/package/@scania/tegel)
- [X] I have followed the installation guide.

### Package versions

@scania/tegel-react 1.4.0

### Browser

Chrome

### Framework

React

### Version

React 

### Reproduction steps

1. Add the component
2. Go the http://tds-storybook.tegel.scania.com/?path=/story/patterns-navigation--few-navigation-items
3. Try to add the det component

### Expected behaviour

Component x should be titled with controls.

### Console errors

Add warning/error message

### Contact information

carl-fredrik.arvidson@scania.com

**Comment by theJohnnyMe** [comment]
We spoke to user, issue was in mistaken understanding of functionality of Patterns page.
