### ISSUE TITLE
[Feature Request]: Allow passing offset values as props to tds-tooltip

### ISSUE THREAD

**Issue by sapostol** [scania-digital-design-system/tegel#509]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/tegel/issues) reported
- [X] I have checked the latest version if the feature exist there

### Type of feature request

Functionality

### What is your feature request?

We want to be able to position the tegel tooltip component to a different space in relation to its associated reference element, 

### Background

Currently the tooltip has the offsets predefined, it opens up with a space of 8 between the tooltip and the reference element and it considers the vertical top position 0 of the browser bar when calculating if the content of the tooltip fits in the viewport

### Idea

allow developers to pass different numbers to the offset properties of the popover core through teh tds-tooltip component's props

![875febc8-52a4-4b4d-aedd-e627bf3dde8d](https://github.com/scania-digital-design-system/tegel/assets/14072167/40391980-374b-4818-8b42-a8369df4e83a)

### Goals and objectives

We would like the tooltip to appear with a narrower space between it and the reference element (4 instead of 8) and set the top position to be the height of the navbar in order for the tooltip to consider it when calculating if the content fits between the reference element and the navbar and not appear on top or under the navigation element
![9ea16e66-080d-40f0-8b16-5a8d75910972](https://github.com/scania-digital-design-system/tegel/assets/14072167/2940b4a0-5081-4e0b-98d1-1fa450ffabba)

### Contact information

simona.apostol@scania.com

**Comment by mJarsater** [comment]
Should be fixed in: https://github.com/scania-digital-design-system/tegel/pull/516
