### ISSUE TITLE
[Feature Request]: Possibility to click on a specific day on the datepicker

### ISSUE THREAD

**Issue by mmexvr** [scania-digital-design-system/tegel#510]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/tegel/issues) reported
- [X] I have checked the latest version if the feature exist there

### Type of feature request

Functionality

### What is your feature request?

When using datepicker ,right now, there is an event called `tdsonchange`, so when clicking and switch date it will trigger on change. 

In the picture we want to trigger on change only when click within the green square, not the arrows also

![Screenshot 2024-02-15 at 14 35 43](https://github.com/scania-digital-design-system/tegel/assets/35451568/79ffaf2a-5bf1-44c5-950a-26ec52faf2bb)

### Background

We have a scenario when you switch date it will load data, for example from 8 jan to 9 jan, which does work with current solution. 

**But the problem** is that when you lets say switch month with the arrows on top. That also triggers on change event which will load the date for next month. We only want to trigger on change when clicking a picked date(day), not when switch between month.

In the picture we want to trigger on change only when click within the green square, not the arrows also

![Screenshot 2024-02-15 at 14 35 43](https://github.com/scania-digital-design-system/tegel/assets/35451568/79ffaf2a-5bf1-44c5-950a-26ec52faf2bb)

### Idea

Maybe add a seperate event, TdsOnChangeDay, that we can listen to, instead of regular on change event.

Another solution would be that you send in the current event, what is being clicked, so if you click a day or the arrows on the top it will send in the event that data, and we can build a condition around it at least. 

### Goals and objectives

We would like only to trigger change on when the user clicks on the dates not on any of the buttons around the datepicker for loading data

### Timeline

Prefer soon :)

**Comment by theJohnnyMe** [comment]
@mmexvr  - Did an upper fix do any help for you?

**Comment by theJohnnyMe** [comment]
Closing this issue as a fix went out in release 1.6.1.
