### ISSUE TITLE
[Bug report]: Text field read only with icon suffix

### ISSUE THREAD

**Issue by apparecidoo** [scania-digital-design-system/tegel#522]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/tegel/issues) reported.
- [X] I have checked the latest version if the bug exist there. See all available packages at [npmJS.com](https://www.npmjs.com/package/@scania/tegel)
- [X] I have followed the installation guide.

### Package versions

@scania/tegel@1.6.0

### Browser

Chrome

### Framework

Angular

### Version

Angular 16

### Reproduction steps

1. Copy and paste the code example

### Code example

```
<tds-text-field type="text" size="lg" state="default" label="Label" label-position="no label" read-only no-min-width placeholder="Placeholder">
    <tds-icon slot="suffix" name="truck" size="20px"></tds-icon>
  </tds-text-field>
```

### Expected behaviour

Not override the icons or text

**Comment by mJarsater** [comment]
Might be an expected behaviour from design? @theJohnnyMe 

I would recommend conditionally toggling the suffix icon if readonly is true?

**Comment by theJohnnyMe** [comment]
Adding an image here so we understand what it is about:

![Screenshot 2024-03-12 at 15 15 24](https://github.com/scania-digital-design-system/tegel/assets/17004063/4669a34a-a0c8-4c3c-9b15-0269bae15018)

I am pinging our designers to check what is expected behavior here. We will keep you posted.

**Comment by theJohnnyMe** [comment]
I got input from designers: Long story short -> "When using suffix icon in read-only state, read-only state icon takes priority and suffix icon should be hidden"
@apparecidoo: I did update in PR for that so you do not have to do anything atm, just be patient, I think we will push this out this Thursday in a release so once you upgrade your code you will have this change in too ;)

**Comment by theJohnnyMe** [comment]
Closing the issue as PR is merged. Stayed tuned for the upcoming release.
