### ISSUE TITLE
[Bug report]: Cannot set properties of undefined (setting 'value')

### ISSUE THREAD

**Issue by ZakirQamar** [scania-digital-design-system/tegel#524]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/tegel/issues) reported.
- [X] I have checked the latest version if the bug exist there. See all available packages at [npmJS.com](https://www.npmjs.com/package/@scania/tegel)
- [X] I have followed the installation guide.

### Package versions

"@scania/tegel-angular": "^1.6.0"

### Browser

Chrome

### Framework

Angular

### Reproduction steps

1. Add tds dropdown to your page
2. use angular reactive form 
3. bind dropdown options dynamically using a list created/initialized in typescript
4: assign default value

### Code example

<tds-dropdown
            ngDefaultControl
            name="market"
            default-value="FR"
            placeholder=""            
            label="Market"
            label-position="outside">  
              <ng-container *ngFor="let market of configuratorService.markets; let idx = index">
                <tds-dropdown-option [value]="market.code">
                  {{ market.name }}
                </tds-dropdown-option>
              </ng-container>
          </tds-dropdown>

### Screenshots

1: set default value is not working..
![image](https://github.com/scania-digital-design-system/tegel/assets/16921625/de419fc8-4de5-4e8f-bfb0-c407341c79f6)

2: drop down select event is throwing error
![image](https://github.com/scania-digital-design-system/tegel/assets/16921625/81b83a9d-ff67-4de7-beff-b8b15e6a9b0d)

### Expected behaviour

1: The tds dropdown should work with the default value.
2: The tds dropdown shouldn't throw any errors on dropdown select

### Console errors

ERROR Error: Uncaught (in promise): TypeError: Cannot set properties of undefined (setting 'value')

**Comment by mJarsater** [comment]
I think you would want to user `default-value` and not `value` for setting a default value. See: https://tds-storybook.tegel.scania.com/?path=/story/components-dropdown--default&args=defaultOption:Option+1&globals=backgrounds.value:!hex(F9FAFB)

**Comment by ZakirQamar** [comment]
Sorry for the incomplete information. Yes, I am using the 'default-value' property, and it works when I use a static value(predefined options) in the dropdown options. However, it doesn't work when we load the options data using a loop.

e.g.
<tds-dropdown
            ngDefaultControl
            name="market"
            default-value="FR"
            placeholder=""            
            label="Market"
            label-position="outside">  
              <ng-container *ngFor="let market of configuratorService.markets; let idx = index">
                <tds-dropdown-option [value]="market.code">
                  {{ market.name }}
                </tds-dropdown-option>
              </ng-container>
          </tds-dropdown>

**Comment by mJarsater** [comment]
@ZakirQamar glad to hear! 

However, this should still be fixed. We should add a listener that checks the `default-value` ones the children change. 
Ping @theJohnnyMe

**Comment by theJohnnyMe** [comment]
@ZakirQamar would anything change if you use prop `[defaultValue]` instead of attribute `default-value`? Please try it out and let me know if anything is different.

**Comment by ZakirQamar** [comment]
Hi, tried with the [defaultValue], but no luck :(

**Comment by theJohnnyMe** [comment]
@ZakirQamar  - I made potential fix for this here: https://github.com/scania-digital-design-system/tegel/pull/599 Please check it out when you have time :) Also I can pack code so you test on you local too to check if it improves it.

**Comment by theJohnnyMe** [comment]
Fix is released in version 1.8.1
