### ISSUE TITLE
[Feature Request]: Time format control in Datetime component

### ISSUE THREAD

**Issue by AnReghunath** [scania-digital-design-system/tegel#526]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/tegel/issues) reported
- [X] I have checked the latest version if the feature exist there

### Type of feature request

Functionality

### What is your feature request?

Datetime component is missing the control where we can set it to 24h format or 12h format
<img width="388" alt="Screenshot 2024-02-22 at 15 53 24" src="https://github.com/scania-digital-design-system/tegel/assets/100352471/fba9e28a-238b-4162-b977-fde46daabfd7">

### Background

To access the 24h format within our web app, windows users seem to need to change regional settings on their system. This isnt ideal for them because we have users in various regions. We want to be able to set the format from within our web app so that it is not tied up with the user's personal system settings 

### Goals and objectives

Ideally a simple control in the component where we set 12h or 24h format 

Alternatively, it would work for us if it were 24h at all times because this is the format of all other times we display throughout our web app

### Timeline

As soon as possible because our UI is being used on a daily basis by scania troubleshooters

### Contact information

cstt.support@scania.com

**Comment by mJarsater** [comment]
I think, since this is just using the native `input type=date` this isn't really possible to config. It's gonna be based on browser and OS settings from the user.

**Comment by mJarsater** [comment]
See: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time

**Comment by mJarsater** [comment]
Closing this. This feature should be implemented ones a fully custom date/time picker is implemented.
