### ISSUE TITLE
[Bug report]: TdsDropdown multiselect does not emit selected values

### ISSUE THREAD

**Issue by Patrick2607** [scania-digital-design-system/tegel#529]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/tegel/issues) reported.
- [X] I have checked the latest version if the bug exist there. See all available packages at [npmJS.com](https://www.npmjs.com/package/@scania/tegel)
- [X] I have followed the installation guide.

### Package versions

@scania/tegel-angular: 1.6.1

### Browser

Firefox

### Framework

Angular

### Version

Angular 16.2.0

### Reproduction steps

1. Add `TdsDropdown` html element with the 'multiselect' property
2. Bind a `formControl` to it
3. Subscribe to the `formControl.valueChanges` observable and log the emitted value
4. On the webpage, (de)select one or multiple values

### Code example

```html
<tds-dropdown
  ngDefaultControl
  [formControl]="form.controls.groups"
  label="Groups"
  label-position="inside"
  placeholder="None"
  size="lg"
  open-direction="auto"
  multiselect>
  <tds-dropdown-option
    *ngFor="let group of groups$ | async"
    [value]="group.id">
    {{ group.name }}
  </tds-dropdown-option>
</tds-dropdown>
```

```typescript
export class MyComponent {
  private readonly fb = inject(FormBuilder);

  readonly groups$ = of([
    { id: 1, name: 'Group 1' },
    { id: 2, name: 'Group 2' },
    { id: 3, name: 'Group 3' },
  ] satisfies GroupModel[]);

  readonly form = this.fb.group({
    // Other form properties
    groups: this.fb.control<number[]>([]),
  });
}
```

The problem is that when you (de)select something, it emits the value of the item that was clicked, not the entire array of selected values. This means that my form control is invalid.

### Expected behaviour

Component `TdsDropdown` with `multiselect` should emit all selected values as array on (de)selection of an item.

Example of what it should emit (order of the items in the array does not matter):
Initial state: []
Click 1: [1]
Click 3: [1, 3]
Click 2: [1, 3, 2]
Click 3: [1, 2]
Click 1: [2]
Click 2: []

### Contact information

patrick.groot.koerkamp@scania.com

**Comment by theJohnnyMe** [comment]
The issue is no longer present. It is tested on https://angular-demo.tegel.scania.com/form/simpleform by selecting Norway and selecting and deselecting a couple of Norweigan towns. The console was showing all correct values in the array.
