### ISSUE TITLE
[Bug report]: TdsTextField not marked as 'touched' after unfocusing

### ISSUE THREAD

**Issue by Patrick2607** [scania-digital-design-system/tegel#530]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/tegel/issues) reported.
- [X] I have checked the latest version if the bug exist there. See all available packages at [npmJS.com](https://www.npmjs.com/package/@scania/tegel)
- [X] I have followed the installation guide.

### Package versions

@scania/tegel-angular: 1.6.1

### Browser

Firefox

### Framework

Angular

### Version

Angular 16.2.0

### Reproduction steps

1. Add `<tds-text-field>` to html template
2. Add `formControl` property to it
3. Log or render the `touched` property
4. Click inside the textbox
5. Click outside the textbox

### Code example

```html
<form [formGroup]="testForm">
  <tds-text-field
    ngDefaultControl
    [formControl]="testForm.controls.text"
    type="text"
    size="lg"
    label="Bugreport"
    label-position="inside"
    placeholder="Bugreport" />

  <p>Touched: {{ testForm.controls.text.touched }}</p>
</form>
```

```typescript
interface TestForm {
  text: FormControl<string | null>;
}

@Component({...})
export class TestComponent {
  readonly testForm = this.fb.group<TestForm>({
    text: this.fb.control(''),
  });
}
```

Now I have temporarily solved this issue by creating a directive for the `tds-text-field`. I manually mark the control as dirty and subsequently mark the view as changed in the `tdsBlur()` handle:
```typescript
@Directive({ selector: 'tds-text-field[tdsExt]' })
export class TdsTextFieldExtDirective implements OnDestroy {
  private readonly tdsTextField = inject(TdsTextField);
  private readonly cdr = inject(ChangeDetectorRef);

  @Input({ alias: 'formControl', required: true }) control!: FormControl;

  private readonly tdsBlurSub = this.tdsTextField.tdsBlur
    .pipe(
      tap(() => {
        this.control.markAsTouched();
        this.cdr.markForCheck();
      })
    )
    .subscribe();

  ngOnDestroy(): void {
    this.tdsBlurSub.unsubscribe();
  }

  // ...
}
```

### Screenshots

Current:
![tds-text-field_current](https://github.com/scania-digital-design-system/tegel/assets/9799823/05480642-47ca-44b4-a39c-59355307909a)

Expected:
![tds-text-field_expected](https://github.com/scania-digital-design-system/tegel/assets/9799823/e5613d91-c790-4003-baf1-4d0248d4889c)

### Expected behaviour

When a user focuses on a text field and subsequently unfocuses, the field should be marked as `touched`.

### Contact information

patrick.groot.koerkamp@scania.com

**Comment by mJarsater** [comment]
Since we are working with custom events the directive you have created above might be the only solution. And since we aren't really building angular components (web-components wrapped in angular) I don't think we can include this directive and support it out of the box.

I'm guessing touched runs on "blur" but we can't emit a native blur event, and that's why we have added the "tdsBlur"

**Comment by adarean5** [comment]
Hey @Patrick2607 , we are also using the tegel-angular package on my project and I decided to create an MR that adds reactive form support from tegel.
You can check out the PR here: https://github.com/scania-digital-design-system/tegel/pull/598

This is the beta version that contains the changes: https://www.npmjs.com/package/@scania/tegel-angular/v/1.8.0-ng-form-beta.2

Could you install this version and test if it solves your issue?

**Comment by theJohnnyMe** [comment]
The user confirmed that the issues are gone after updating to the newer version of code that contains Jernej's changes.
