### ISSUE TITLE
[Bug report]: `tds-breadcrumbs` wrongfully sets class `last` to first element

### ISSUE THREAD

**Issue by AndreasRasovicScania** [scania-digital-design-system/tegel#549]
### Requirements before reporting

- [x] No duplicated [issue](https://github.com/scania-digital-design-system/tegel/issues) reported.
- [X] I have checked the latest version if the bug exist there. See all available packages at [npmJS.com](https://www.npmjs.com/package/@scania/tegel)
- [X] I have followed the installation guide.

### Package versions

@scania/tegel: 1.6.1, @scania/tegel-angular: 1.6.1

### Browser

Chrome

### Framework

Angular

### Version

Angular 16

### Reproduction steps

...

### Code example

```
<tds-breadcrumbs>
  <tds-breadcrumb *ngFor="let crumb of breadcrumbs; index as i">
    <tds-link>
      <label (click)="navigate(crumbPath(i, breadcrumbs))">{{ crumb }}</label>
    </tds-link>
  </tds-breadcrumb>
</tds-breadcrumbs>
```

### Screenshots

![image](https://github.com/scania-digital-design-system/tegel/assets/163417029/a35b81c1-9095-4fbe-b994-7d30355799bb)
![image](https://github.com/scania-digital-design-system/tegel/assets/163417029/90e87e11-d0c4-4fe5-b6af-56fe301bf02d)

### Expected behaviour

`last` class should be added to the last `tds-breadcrumb` and not the first.

### Console errors

No errors are shown in the console.

### Contact information

[andreas.rasovic@scania.com](mailto:andreas.rasovic@scania.com), [abdelrhman.safwat@scania.com](mailto:abdelrhman.safwat@scania.com)

**Comment by theJohnnyMe** [comment]
@AndreasRasovicScania  - Can you please check if you have used "current" prop on last <tds-breadcrumb>? That one is in control of "last" breadcrumb. As we do not know all uses cases we left it up to user to define whenever he/she thinks is "last".

**Comment by AndreasRasovicScania** [comment]
@theJohnnyMe tried and it's still the same result. The last element has the `current` class but the first element is still `last`:
![image](https://github.com/scania-digital-design-system/tegel/assets/163417029/2e746c92-caaa-4921-ac39-4a05460a9416)
![image](https://github.com/scania-digital-design-system/tegel/assets/163417029/eaee6600-dd03-447d-8aee-07caadc66ad0)

**Comment by AndreasRasovicScania** [comment]
NVM. Solved it like this:
```javascript
<tds-breadcrumbs>
  <tds-breadcrumb
    *ngFor="let crumb of breadcrumbs; index as i"
    [class.last]="i + 1 === breadcrumbs?.length ? '' : null"
    [current]="i + 1 === breadcrumbs?.length ? '' : null"
    (click)="navigate(crumbPath(i, breadcrumbs))">
    <tds-link>
      <label (click)="navigate(crumbPath(i, breadcrumbs))">{{ crumb }}</label>
    </tds-link>
  </tds-breadcrumb>
</tds-breadcrumbs>
```

**Comment by theJohnnyMe** [comment]
@theJohnnyMe nice to hear it worked out ;) 
Here is also example we played with in our Angular demo page: https://github.com/scania-digital-design-system/tegel-angular-demo/tree/main/src/app/navigation/breadcrumbs
