### ISSUE TITLE
[Bug report]: tds-breadcrumbs shows an extra icon (Angle bracket) after the last element

### ISSUE THREAD

**Issue by SonOfSafwat** [scania-digital-design-system/tegel#556]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/tegel/issues) reported.
- [X] I have checked the latest version if the bug exist there. See all available packages at [npmJS.com](https://www.npmjs.com/package/@scania/tegel)
- [X] I have followed the installation guide.

### Package versions

@scania/tegel: 1.6.1, @scania/tegel-angular: 1.6.1

### Browser

Chrome

### Framework

Angular

### Version

Angular 16

### Reproduction steps

1. Go to Tegel Angular Demo https://angular-demo.tegel.scania.com/
2. Navigate to Text page and then Subpage 
3. You will see the extra angle bracket 
4. If the access the page directly the angle bracket is not shown

### Code example

<tds-breadcrumbs>
      <ng-container *ngFor="let segment of segments; let idx = index;  last as isLast">
        <tds-breadcrumb [current]="isLast">
          <a class="capitalize" [routerLink]="segment.path">{{ segment.title }}</a>
        </tds-breadcrumb>
      </ng-container>
    </tds-breadcrumbs>

### Screenshots

![image](https://github.com/scania-digital-design-system/tegel/assets/13849680/a842caf3-b24a-4db2-956d-728700926099)

![image](https://github.com/scania-digital-design-system/tegel/assets/13849680/0c4dc5b0-892e-4774-9922-ecabdd10c570)

### Expected behaviour

No angle bracket to be shown after the last item

### Console errors

N/A

### Contact information

Abdelrhman.Safwat@scania.com

**Comment by timrombergjakobsson** [comment]
@SonOfSafwat thanks for reporting the bug!

**Comment by nathalielindqvist** [comment]
@SonOfSafwat this bug has been rectify and a fix for it is available in the latest version of our packages 🙂
