### ISSUE TITLE
[Bug report]: missing padding in Table header in compact mode

### ISSUE THREAD

**Issue by jolalab** [scania-digital-design-system/tegel#557]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/tegel/issues) reported.
- [X] I have checked the latest version if the bug exist there. See all available packages at [npmJS.com](https://www.npmjs.com/package/@scania/tegel)
- [X] I have followed the installation guide.

### Package versions

@scania/tegel: ^1.6.0

### Browser

Chrome

### Framework

Angular

### Version

Angular 16

### Reproduction steps

1. Create a Tegel Table with a header 
2. Set it to use compact mode
3. Write a long text in one of the columns
4. Shrink the window until the line breaks into multiple rows
5. Observe how there is no padding over or under the text

### Code example

```html
   <tds-table
        [responsive]="true"
        [compactDesign]="true"
        [noMinWidth]="true"
    >
                <tds-table-header>
                        <tds-header-cell
                            [cellValue]="A very very long text that keeps going and going and never ends and just keeeps going until the bitter end and never stops because it just keeps going and going and just continues through time and space into eternity and just continues after that too..."
                            sortable="true"
                       >
                </tds-table-header>

                <tds-table-body>
                     <tds-table-body-row></tds-table-body-row>
                 </tds-table-body>                 
</tds-table>
```

### Screenshots

![image](https://github.com/scania-digital-design-system/tegel/assets/164156972/0cd8b82c-4285-468e-8dcc-884ab915933c)

### Expected behaviour

There should be padding at the top and bottom even when the text breaks into multiple rows and when it is in compact mode

### Console errors

Add warning/error message

### Contact information

jonatan.lampa@scania.com

**Comment by nathalielindqvist** [comment]
Hi @jolalab! Thank you for reporting this, a fix for the issue has now been merged and will be available in the next release! :)
