### ISSUE TITLE
[Bug report]: Wrong release title in Github releases.

### ISSUE THREAD

**Issue by mJarsater** [scania-digital-design-system/tegel#570]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/tegel/issues) reported.
- [X] I have checked the latest version if the bug exist there. See all available packages at [npmJS.com](https://www.npmjs.com/package/@scania/tegel)
- [X] I have followed the installation guide.

### Package versions

@scania/tegel@1.7.0

### Browser

Chrome

### Framework

Angular

### Reproduction steps

Should be 1.7.0.

![Screenshot 2024-03-27 at 09 11 22](https://github.com/scania-digital-design-system/tegel/assets/62651103/f4ea973c-2f9e-415c-9193-0e1d1a7f95ea)

### Expected behaviour

Release should be 1.7.0.

**Comment by timrombergjakobsson** [comment]
@mJarsater thanks man :)!

**Comment by timrombergjakobsson** [comment]
Should be updated now to correct version!
