### ISSUE TITLE
[Feature Request]: Programmatically expand table rows

### ISSUE THREAD

**Issue by adarean5** [scania-digital-design-system/tegel#575]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/tegel/issues) reported
- [X] I have checked the latest version if the feature exist there

### Type of feature request

Functionality

### What is your feature request?

Currently, the `tds-table-body-row-expandable` component can only be expanded by clicking on the arrow button to the left of the row, but it cannot be expanded programmatically.
The `tds-table-body-row-expandable` should be expandable programmatically.

### Background

I have a use case where the first row in the table should be automatically expanded by default. Currently, I am unable to achieve this since the `tds-table-body-row-expandable` does not allow me to expand it programmatically.

### Idea

An `isExpanded` prop could be added that would control whether or not the table is expanded. The expanded state should be ignored if the user expands the row on their own.

**Comment by patrikhultgren** [comment]
I can confirm that we need this feature in the SSI team too.

**Comment by frogleif** [comment]
big +1 on this one, our usability would go up insanely much! As of now, it is impossible for our users to keep track on items they are working with. Thank you! /JP SSI@KJE

**Comment by theJohnnyMe** [comment]
Our new colleague @mistermalm is looking into this at the moment, expect an update soon. :)

**Comment by patrikhultgren** [comment]
I would like to compliment the idea. What about adding a callback function that will be called when the user presses the expand/collapse button? Then the consuming app will have full control of the behavior and the isExpanded attribute is the only thing that decides if it’s expanded or closed. For example, maybe the consuming app also would like to log statistics when expanding and closing the row. Then that’s possible. So what I want is two way binding of isExpanded.

**Comment by frogleif** [comment]
That sounds like really good functionality, and a great idea! +1

**Comment by theJohnnyMe** [comment]
We are looking into approach of having a prop like defaultExpanded that will be checked on connected callback + having a method/s to alter the open state. Something similar we have for modal component. How does that idea sounds?

**Comment by patrikhultgren** [comment]
I think that would work too. But in general I think it’s better to depend on props instead of exposing methods. For example when using the modal I never call closeModal() or openModal(). Instead I always set show to true and renders the modal conditionally.

**Comment by adarean5** [comment]
@patrikhultgren In my opinion the component should still expand the row without requiring additional setup and properties from the consumer. Having to keep the `expanded` state for each table row would needlessly increase the complexity of components that do not need to toggle the rows programmatically. I think it would be best to expose an `isExpanded` prop that would toggle the expanded state of the table when changed.  I like the idea of having an event emitter for when a row is expanded though.
