### ISSUE TITLE
[Bug report]: Angular with esbuild fails

### ISSUE THREAD

**Issue by ExeAy** [scania-digital-design-system/tegel#590]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/tegel/issues) reported.
- [X] I have checked the latest version if the bug exist there. See all available packages at [npmJS.com](https://www.npmjs.com/package/@scania/tegel)
- [X] I have followed the installation guide.

### Package versions

@scania/tegel-angular: 1.7.0

### Framework

Angular

### Version

Angular 16+

### Reproduction steps

1. Create or use an angular project that uses esbuild. This is default in Angular 17.
2. Import `@scania/tegel-angular` and use a tegel component.
3. Build the project, `ng build --verbose`

Then we get the following error
`Could not resolve "@scania/tegel-angular"`

Reproduction repo exists here: https://github.com/adarean5/tegel-angular-esbuild-issue-repro

### Code example

<div>....

### Screenshots

![image](https://github.com/scania-digital-design-system/tegel/assets/22538204/ef6ee928-a5d1-4688-9bd1-07f9faf42c34)

### Expected behaviour

It should be possible to use `@scania/tegel-angular` with esbuild.

### Contact information

hannes.falk@scania.com

**Comment by theJohnnyMe** [comment]
Issue is resolved in [@scania/tegel-angular-17](https://www.npmjs.com/package/@scania/tegel-angular-17)
