### ISSUE TITLE
[Feature Request]: programmatically toggle the state of tds-side-menu-dropdown 

### ISSUE THREAD

**Issue by SonOfSafwat** [scania-digital-design-system/tegel#609]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/tegel/issues) reported
- [X] I have checked the latest version if the feature exist there

### Type of feature request

Functionality

### What is your feature request?

Expose an api to expand and collapse tds-side-menu-dropdown programmatically 

### Background

we have a search functionality within the side menu items and it would enhance user experience to show the nested search results if they match what they're looking for

### Idea

expose the collapsed property or expose a toggleCollapseState function

### Contact information

abdelrhman.safwat@scania.com

**Comment by theJohnnyMe** [comment]
I am closing it as the fix was released.
