### ISSUE TITLE
[Bug report]: TdsModal does not respect the "show" property

### ISSUE THREAD

**Issue by quaspar** [scania-digital-design-system/tegel#614]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/tegel/issues) reported.
- [X] I have checked the latest version if the bug exist there. See all available packages at [npmJS.com](https://www.npmjs.com/package/@scania/tegel)
- [X] I have followed the installation guide.

### Package versions

"@scania/tegel-react": "1.8.1"

### Browser

Chrome

### Framework

React

### Version

React 18.3.1

### Reproduction steps

1. Add TdsModal with property "show" set to true.
2. Click close button or backdrop

### Code example

Demo:
https://quaspar.github.io/tegel-modal-bug-report/

Code:
https://github.com/quaspar/tegel-modal-bug-report/blob/main/src/App.js

### Screenshots

Add/Copy screenshot here

### Expected behaviour

Modal should not close as long as the show prop is true.

### Console errors

Add warning/error message

### Contact information

caspar.behrendt@scania.com

**Comment by Lunkan89** [comment]
@quaspar I believe that you can reach this behavior by not using a `selector` and adding `onTdsClose={e => e.preventDefault()}`
Then showing and hiding the modal should only rely on the toggling of the show prop.
Let me know if this solution works for you.

**Comment by theJohnnyMe** [comment]
Not considered an issue. Seems like lack of information. Closing it. Reopen if provided solution does not work.

**Comment by quaspar** [comment]
Hello, thank you for your replies. Where am I supposed to add the onTdsClose property? I've added it to the modal component, and also added a console log, but no event seems to be caught, and modal closing is not prevented. See links to code and demo above.
