### ISSUE TITLE
[Bug report]: Unwanted extra space appears to the right of an collapsed side menu item in desktop

### ISSUE THREAD

**Issue by patrikhultgren** [scania-digital-design-system/tegel#620]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/tegel/issues) reported.
- [X] I have checked the latest version if the bug exist there. See all available packages at [npmJS.com](https://www.npmjs.com/package/@scania/tegel)
- [X] I have followed the installation guide.

### Package versions

@scania/tegel 1.8.2

### Browser

Chrome

### Framework

React

### Version

React 18.2.0

### Reproduction steps

1. Add component Side Menu.
2. Set collapsed and persistent to true.
3. Look at it in desktop.
4. An unwanted space of 1px appears to the right of the menu items.

### Code example

`<tds-side-menu collapsed persistent aria-label="Side menu" id="demo-side-menu"><tds-side-menu-item>
  <button>
          <tds-icon name="star" size="24px"></tds-icon>
          Values
        </button>
      </tds-side-menu-item></tds-side-menu>`

### Screenshots

<img width="220" alt="side-menu" src="https://github.com/scania-digital-design-system/tegel/assets/1917147/6a6857db-fa36-431d-8e78-a339acface3b">

### Expected behaviour

That extra space of 1px should be removed.

### Contact information

patrik.hultgren@scania.com

**Comment by theJohnnyMe** [comment]
Merged, closing the issue.
