### ISSUE TITLE
[Feature Request]: Make it possible to remove last accordion item bottom border 

### ISSUE THREAD

**Issue by patrikhultgren** [scania-digital-design-system/tegel#625]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/tegel/issues) reported
- [X] I have checked the latest version if the feature exist there

### Type of feature request

Functionality

### What is your feature request?

Make it possible to remove last accordion item bottom border.

### Background

In the SSI team I’m building a filter component using an accordion to group the filters. To fulfill the design I need to hide the last accordion item bottom border.

### Idea

Add prop for removing the last accordion item bottom border.

### Goals and objectives

The outcome should look like this:
<img width="957" alt="accordion" src="https://github.com/scania-digital-design-system/tegel/assets/1917147/eacf41d4-84c2-40dd-9dad-959749e7d908">

### Pull request

https://github.com/scania-digital-design-system/tegel/pull/626

### Contact information

patrik.hultgren@scania.com

**Comment by kaspertronstad** [comment]
Removing the last divider / border in a list of accordions visually indicates to users that there is no more information available. The current component creates visual confusion, making users think there is more information below the fold, but they can’t access it, which can make the UI / page / function seem broken.

**Comment by theJohnnyMe** [comment]
Thank you both @patrikhultgren and @kaspertronstad for contribution in Tegel with this improvement! It is merged and we expect to have it out tomorrow ;)
