### ISSUE TITLE
[Bug report]: tds-popover-menu not closing when triggering another tds-popover-menu to open

### ISSUE THREAD

**Issue by jolalab** [scania-digital-design-system/tegel#632]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/tegel/issues) reported.
- [X] I have checked the latest version if the bug exist there. See all available packages at [npmJS.com](https://www.npmjs.com/package/@scania/tegel)
- [X] I have followed the installation guide.

### Package versions

@scania/tegel:1.8.0

### Browser

Chrome

### Framework

Angular

### Version

Angular 17

### Reproduction steps

1. Add 2 tds-popover-menu component next to each other with 2 different triggers
2. Click on the first one of them
3. [The menu opens]
4. Click on the second one
5. [The other menu opens (but the first one does not close)]

### Code example

<div>....

### Screenshots

Add/Copy screenshot here
![Screenshot 2024-05-29 at 15 20 55](https://github.com/scania-digital-design-system/tegel/assets/164156972/509f42be-08bd-4561-92b1-be01834205d8)

### Expected behaviour

When you have 1 menu open and trigger the other one to open, the first one should close

### Console errors

Add warning/error message

### Contact information

jonatan.lampa@scania.com

**Comment by theJohnnyMe** [comment]
I think I fixed this here: https://github.com/scania-digital-design-system/tegel/pull/595

Please check it, maybe you just need to bump version of Tegel to newer one as this one was released in 1.8.1

**Comment by jolalab** [comment]
Hey, thanks for pointing that out! I should have bumped to latest minor version also before reporting the bug, but thank you anyways! 
And great work! Appreciate your quick responses.

**Comment by jolalab** [comment]
Closing this one!
