### ISSUE TITLE
[Bug report]: Remove `BREAKING CHANGE 🚩` title in release notes

### ISSUE THREAD

**Issue by mJarsater** [scania-digital-design-system/tegel#638]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/tegel/issues) reported.
- [X] I have checked the latest version if the bug exist there. See all available packages at [npmJS.com](https://www.npmjs.com/package/@scania/tegel)
- [X] I have followed the installation guide.

### Package versions

@scania/tegel 1.9.0

### Reproduction steps

Remove the `BREAKING CHANGE 🚩` title from the release notes:

### Screenshots

![Screenshot 2024-05-31 at 08 37 18](https://github.com/scania-digital-design-system/tegel/assets/62651103/a98e61de-86e2-4b7e-af84-f8d50c699721)

### Expected behaviour

If there are not breaking changes the title is not needed.

**Comment by mJarsater** [comment]
I know I can also just remove this, put I don't wanna poke around if you had this in by intention

**Comment by timrombergjakobsson** [comment]
> I know I can also just remove this, put I don't wanna poke around if you had this in by intention

no, it's a mistake! Thanks! Updated now https://github.com/scania-digital-design-system/tegel/releases/tag/%40scania%2Ftegel%401.9.0
