### ISSUE TITLE
[Bug report]: Can't import CSS after upgrading to Tegel 1.9.0

### ISSUE THREAD

**Issue by patrikhultgren** [scania-digital-design-system/tegel#640]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/tegel/issues) reported.
- [X] I have checked the latest version if the bug exist there. See all available packages at [npmJS.com](https://www.npmjs.com/package/@scania/tegel)
- [X] I have followed the installation guide.

### Package versions

@scania/tegel 1.9.0

### Browser

Chrome

### Framework

React

### Version

18.2.0

### Reproduction steps

1. Clone repo [tegel-react-demo](https://github.com/scania-digital-design-system/tegel-react-demo)
2. Upgrade @scania/tegel-react to 1.9.0
3. npm run start

### Screenshots

<img width="1686" alt="error" src="https://github.com/scania-digital-design-system/tegel/assets/1917147/32c1338b-d444-4599-a05b-73047b58884f">

### Expected behaviour

The app should start without crashing.

### Contact information

patrik.hultgren@scania.com

**Comment by theJohnnyMe** [comment]
Fixed in version 1.9.1
