### ISSUE TITLE
[Bug report]: The expand-row slot expands the entire table instead of overflowing

### ISSUE THREAD

**Issue by adarean5** [scania-digital-design-system/tegel#645]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/tegel/issues) reported.
- [X] I have checked the latest version if the bug exist there. See all available packages at [npmJS.com](https://www.npmjs.com/package/@scania/tegel)
- [X] I have followed the installation guide.

### Package versions

@scania/tegel: 1.9.1

### Browser

Chrome

### Framework

Angular

### Version

Angular 17

### Reproduction steps

1. Create a component that is wider than your table
2. Place it in the "expand-row" slot in the `tds-table-body-row-expandable` component.
3. Expand the expandable row to display the wide component

### Screenshots

The table with wide content in the expanded area collapsed. The table fits in the modal.
![image](https://github.com/scania-digital-design-system/tegel/assets/15961301/a2246654-ede6-494f-bb66-2cf457606558)

After expanding, the wide content row also expands the entire table and all the columns no longer fit into view.
![image](https://github.com/scania-digital-design-system/tegel/assets/15961301/2e3d9264-153d-4c45-b9da-abb792ffc6ba)

### Expected behaviour

The expand-row should never increase the width of the table.
Instead, the expand row should fit into the container, so the contents can be responsively positioned (for example with display:flex). Any elements, that are wider than the available width inside the `expand-row` slot, should overflow instead of expanding the entire table.

### Console errors

Add warning/error message

### Contact information

jernej.strazisar@scania.com

**Comment by theJohnnyMe** [comment]
Fix released in: @scania/tegel@1.14.0
