### ISSUE TITLE
[Feature Request]: Translations and date format for different cultures in date picker

### ISSUE THREAD

**Issue by cristinaneculita** [scania-digital-design-system/tegel#649]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/tegel/issues) reported
- [X] I have checked the latest version if the feature exist there

### Type of feature request

Functionality

### What is your feature request?

The text that appears on the date picker to have support for translations. Also the format of the date to be adapted to different styles depending on the culture.

![MicrosoftTeams-image (21)](https://github.com/scania-digital-design-system/tegel/assets/4415520/d8b55dd8-fe21-4ee8-8e44-5defeed46e4b)

### Background

We have customers in different countries and all the labels in our application have translations depending on their country. It would be good to also have these date picker have translations.

### Idea

Maybe add a property for culture.

### Goals and objectives

Have the texts in the date picker translated in different languages. Have the date format adapted to different cultures.

### Timeline

It's not urgent, but a nice feature to have.

### Contact information

cristina.neculita@scania.com

**Comment by theJohnnyMe** [comment]
Hi @cristinaneculita, unfortunately, this is not under our control. It depends on the regional and language settings of user's operating system and browser.
