### ISSUE TITLE
[Feature Request]: Compact footer

### ISSUE THREAD

**Issue by HasanVatansever** [scania-digital-design-system/tegel#650]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/tegel/issues) reported
- [X] I have checked the latest version if the feature exist there

### Type of feature request

Design

### What is your feature request?

makes footer, half size, compact

### Background

in some application current footer takes a lot of space, would be better to have it smaller

### Idea

by adding a property such as CompactDesign, it can be made half size

### Goals and objectives

in some application current footer takes a lot of space, would be better to have it smaller

<img width="1726" alt="Screenshot 2024-06-11 at 15 02 52" src="https://github.com/scania-digital-design-system/tegel/assets/8792533/8b0bee19-1221-4eac-ac2f-8409902189e8">

**Comment by theJohnnyMe** [comment]
Released in tegel 1.11.0
