### ISSUE TITLE
[Feature Request]: Inject custom CSS into expandable rows

### ISSUE THREAD

**Issue by former-self** [scania-digital-design-system/tegel#664]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/tegel/issues) reported
- [X] I have checked the latest version if the feature exist there

### Type of feature request

Functionality

### What is your feature request?

tds-body-row-expandable elements should be able to be styled like the normal tds-body-row elements.

Here's an attempt at styling a table with mixed normal and expandable rows, and as you can see nothing happens with the expandable ones:
![image](https://github.com/scania-digital-design-system/tegel/assets/31841236/ef442adc-acff-444d-add4-1ee1308cb2f1)

### Background

Colour is a great tool to highlight significant information in larger tables and the expandable rows are great to let the user be able to see more information about why the data is highlighted without clutter.

### Idea

Adding a "part" attribute to the tr elements would allow easy styling of expandable rows through the ::part() selector ([CSS Shadow Parts](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_shadow_parts))

### Goals and objectives

If expandable rows can be styled with just CSS it would be a success.

If something like this could work I'd be happy. Of course there might be other just as simple solutions and they would be fine too.
tds-body-row.red, tds-body-row-expandable.red::part(row) {
  background-color: red;
}

### Contact information

alexander.powell@scania.com

**Comment by theJohnnyMe** [comment]
The fix is to be released next week.

**Comment by theJohnnyMe** [comment]
Fix is released is version 1.13.0
