### ISSUE TITLE
[Feature Request]: Implement a row click callback for table rows.

### ISSUE THREAD

**Issue by ExeAy** [scania-digital-design-system/tegel#672]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/tegel/issues) reported
- [X] I have checked the latest version if the feature exist there

### Type of feature request

Functionality

### What is your feature request?

I need a row click handler to handle events on a row click. If a row click is enabled we might want to style each rows so that the cursor is a pointer.

### Background

In my case I want to route the user to a details page when the user clicks on a row.

The benefits is that it makes some actions easier to do for the users. Instead of locating a button or a menu item they can just click the row directly.

### Idea

E.g. add a tdsClick event on table-body-row. Also change style on the cursor if tdsClick is defined.

### Goals and objectives

A user can click on a row and a desired action is taken.

**Comment by nathalielindqvist** [comment]
Closing this issue since this feature is now available in the latest version of our packages 🙂
