### ISSUE TITLE
Issue with tds pagination textbox when having three or more digit numbers.

### ISSUE THREAD

**Issue by asi6v5** [scania-digital-design-system/tegel#674]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/tegel/issues) reported.
- [X] I have checked the latest version if the bug exist there. See all available packages at [npmJS.com](https://www.npmjs.com/package/@scania/tegel)
- [X] I have followed the installation guide.

### Package versions

@scania/tegel@1.10.0

### Browser

Chrome

### Framework

Angular

### Version

Angular 17

### Reproduction steps

![image](https://github.com/scania-digital-design-system/tegel/assets/174307337/637c84fd-35ac-4d0f-8638-83f311ebb643)

### Code example

<div>....

### Screenshots

Add/Copy screenshot here

### Expected behaviour

The text in the pagination control should be fully visible.

### Console errors

Add warning/error message

### Contact information

ankita.singh@scania.com

**Comment by theJohnnyMe** [comment]
Issue was addressed in version 1.19.0
