### ISSUE TITLE
[Bug report]: Fixing height for different content of <tds-card>

### ISSUE THREAD

**Issue by aze2d7** [scania-digital-design-system/tegel#718]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/tegel/issues) reported.
- [X] I have checked the latest version if the bug exist there. See all available packages at [npmJS.com](https://www.npmjs.com/package/@scania/tegel)
- [X] I have followed the installation guide.

### Package versions

"@scania/tegel-angular-17": "^1.9.1",

### Browser

Chrome

### Framework

Angular

### Version

Angular 17

### Reproduction steps

1. Create multiple <tds-card> with different card-content
2. Each card will have different height based on the length of the card-content

...

### Code example

<div>....

### Screenshots

![image](https://github.com/user-attachments/assets/410208fa-54e3-40f7-b9d0-4956924515b6)

### Expected behaviour

multiple <tds-card> should have same height irrespective of the card-content so that the cards look uniform on the screen.

### Console errors

Add warning/error message

### Contact information

amena.zeenat@scania.com

**Comment by nathalielindqvist** [comment]
Closing this issue since a fix for it is available in the latest version of our packages 🙂
