### ISSUE TITLE
[Feature Request]: Auto collapse expanded row upon clicking other expandable row in table

### ISSUE THREAD

**Issue by dhananjaysakhare244** [scania-digital-design-system/tegel#739]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/tegel/issues) reported
- [X] I have checked the latest version if the feature exist there

### Type of feature request

Functionality

### What is your feature request?

Possible to automatically collapse the expanded row if user expands a different row
Right now, if user clicks on a different row both are in expanded state.
![image](https://github.com/user-attachments/assets/217f5756-2215-4bdf-ac0a-1781be616e50)

### Background

As user expands many rows without collapsing already opened rows, user gets confused with too much on screen.
It makes it harder when there are so many rows in table that are in expanded state.

### Contact information

dhananjay.sakhare@scania.com

**Comment by ckrook** [comment]
PR: https://github.com/scania-digital-design-system/tegel/pull/758

**Comment by nathalielindqvist** [comment]
Closing this issue since this feature is available in the latest versions of our packages 🙂
