### ISSUE TITLE
[Feature Request]: Add a property to control whether padding is applied to the expanded area of an expanded table row

### ISSUE THREAD

**Issue by patrikhultgren** [scania-digital-design-system/tegel#785]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/tegel/issues) reported
- [X] I have checked the latest version if the feature exist there

### Type of feature request

Functionality

### What is your feature request?

There are times when you may want to utilize the entire expanded area without being restricted by the default padding.

### Background

Our design aims to maximize the full width of the expanded area. Otherwise, it will not present well.

### Idea

Add a property to control whether padding is applied to the expanded area of an expanded table row.

### Contact information

patrik.hultgren@scania.com

**Comment by timrombergjakobsson** [comment]
[Fixed here](https://github.com/scania-digital-design-system/tegel/pull/789)
