### ISSUE TITLE
[Bug report]: <tds-slider/> component non-responsive  on touchscreen devices

### ISSUE THREAD

**Issue by acivgin** [scania-digital-design-system/tegel#812]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/tegel/issues) reported.
- [X] I have checked the latest version if the bug exist there. See all available packages at [npmJS.com](https://www.npmjs.com/package/@scania/tegel)
- [X] I have followed the installation guide.

### Package versions

@scania/tegel: "1.18.0"

### Browser

Chrome

### Framework

Angular

### Version

Angular 15.4.0.

### Reproduction steps

1. Open the application on a touchscreen device (e.g., TV, mobile or tablet).
2. Navigate to a page containing the <tds-slider/> component.
3. Attempt to adjust the slider using touch gestures (swipe or tap).
4. Observe that the slider does not respond to any touch interactions.

When users attempt to interact with the <tds-slider/> component on touch-enabled devices, it does not respond to touch gestures, such as swiping or tapping, to adjust the slider value.
NOTE: minus and plus buttons work as expected

### Code example

```
  <div id="quantity-slider">
          <tds-slider
            #slider
            ngDefaultControl
            formControlName="quantity"
            [max]="maxQuantity"
            [min]="minQuantity"
            step="1"
            [value]="actualQuantity"
            tooltip
            controls
            thumb-size="lg"
            >
          </tds-slider>
        </div>
```

### Screenshots

![image (5)](https://github.com/user-attachments/assets/b2533f02-5453-43bf-ad54-788b97638712)

### Expected behaviour

The <tds-slider/> component should respond to standard touch interactions, allowing users to adjust the slider on touchscreen devices, similar to how it behaves on non-touchscreen (desktop) environments.

### Console errors

"Unable to preventDefault inside passive event listener invocation."

### Contact information

adis.civgin@scania.com

**Comment by Lunkan89** [comment]
@acivgin I have trouble recreating this issue, is it possible for you to create a [StackBlitz](https://stackblitz.com/edit/stackblitz-starters-wbvhkp?description=An%20angular-cli%20project%20based%20on%20@angular/animations,%20@angular/common,%20@angular/compiler,%20@angular/core,%20@angular/forms,%20@angular/platform-browser,%20@angular/platform-browser-dynamic,%20@angular/router,%20core-js,%20rxjs,%20tslib%20and%20zone.js&file=package.json&template=node&title=Angular%20Starter) ?
