### ISSUE TITLE
[Feature Request]: Request for Reset Function in TDS Datetime Control

### ISSUE THREAD

**Issue by ZakirQamar** [scania-digital-design-system/tegel#821]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/tegel/issues) reported
- [X] I have checked the latest version if the feature exist there

### Type of feature request

Functionality

### What is your feature request?

 Include reset method for TDS Datetime.

### Background

Unable to reset the TDS date-time display when a user removes the year. Unlike the TDS dropdown, we don’t have a reset function for TDS datetime. When I click the clear button, it doesn’t reset the display, even though the value is null if the date format isn’t correct.

### Goals and objectives

Ensure TDS datetime control can reset display if a user remove the year.

![image](https://github.com/user-attachments/assets/bd6d0882-b8a7-475a-8844-59de497eb0d2)

**Comment by theJohnnyMe** [comment]
Code with this function is released in version 1.20.0.
