### ISSUE TITLE
[Bug report]: Time picker is not working in firefox and safari (maybe even more)

### ISSUE THREAD

**Issue by ExeAy** [scania-digital-design-system/tegel#887]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/tegel/issues) reported.
- [X] I have checked the latest version if the bug exist there. See all available packages at [npmJS.com](https://www.npmjs.com/package/@scania/tegel)
- [X] I have followed the installation guide.

### Package versions

"@scania/tegel": "^1.20.0"  "@scania/tegel-angular-17": "^1.20.0",

### Browser

Firefox

### Framework

Angular

### Version

Angular 18

### Code sandbox

Try this with different browsers:
https://stackblitz.com/edit/stackblitz-starters-ncg7d7mn?description=An%20angular-cli%20project%20based%20on%20@angular/animations,%20@angular/common,%20@angular/compiler,%20@angular/core,%20@angular/forms,%20@angular/platform-browser,%20@angular/platform-browser-dynamic,%20@angular/router,%20core-js,%20rxjs,%20tslib%20and%20zone.js&file=src%2Fglobal_styles.css,src%2Fmain.ts&template=node&title=Angular%20Starter

### Reproduction steps

1. Add a datetime component in an angular project (maybe others as well?)
2. Open the date picker
3. Check if you get a time picker as well.
...

### Screenshots / Screen recordings

Firefox:
![image](https://github.com/user-attachments/assets/ab3359bb-86f7-4c23-b7db-5193dab47eef)

Edge (Chromium)
![image](https://github.com/user-attachments/assets/5a0077d3-507d-443d-8ae7-009a08a16407)

### Expected behaviour

Time picker should be visible for all major browsers.

### Console errors

Add warning/error message

### Contact information

hannes.falk@scania.com

**Comment by NOMADE55** [comment]
Good news is, its not tegel, bad news is, can't be fixed at the moment 😅
@ExeAy This is a well known bug from firefox and safari.

Refer to [the compatibility table](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local#browser_compatibility) in MDN

**Comment by ckrook** [comment]
We’ll proceed with closing this issue for now, given that it’s tied to a known browser bug outside of our control. If new information surfaces or a workaround becomes available, we can revisit and reopen the issue.
