### ISSUE TITLE
[Feature Request]: Single Row Selection in Data Tables

### ISSUE THREAD

**Issue by hawa1996** [scania-digital-design-system/tegel#97]
### Requirements before reporting

- [X] No duplicated [issue](https://github.com/scania-digital-design-system/tegel/issues) reported
- [X] I have checked the latest version if the feature exist there

### Type of feature request

Functionality

### What is your feature request?

Currently there only exists multi row select, however, it would be nice to also have single row selection in line with the Tegel docs: https://tegel.scania.com/components/table

### Background

In my case I have a data table with 3-4 actions a user can perform. Each action triggers a unique flow, so multi select doesn't make sense in this regard. Being able to single select one row and then select the correct action to take from the data table toolbar is the flow that is desired. 

### Idea

See https://tegel.scania.com/components/table (Single row selection)

### Goals and objectives

See https://tegel.scania.com/components/table (Single row selection)

### Resources

https://tegel.scania.com/components/table

### Contact information

hannes.warnestad@redpill-linpro.com

**Comment by mJarsater** [comment]
Thanks for the request! I'll bring this to our PO and we'll see what we can do. 

Ps, I'm gonna edit some of the links you left since we have changes some of the endpoints on our website.

**Comment by mJarsater** [comment]
This feature request is noted and added to our backlog, will need both design investigation and development work.
